import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import StarsCanvas from "@/components/StarBackground";
// import "./globals.css";

export const metadata = {
  title: "BeDonkey - Video Platform",
  description: "Discover, share, and enjoy videos with the BeDonkey community.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Grotesk:wght@300..700&display=swap"
          rel="stylesheet"
        />
        <link rel="icon" href="/br.png?v=2" />
      </head>
      <body className="bg-black custom-bg-dark overflow-x-hidden">
        {/* Optional animated background */}
        <StarsCanvas />
        <div className="relative z-20 flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}

// import Header from "@/components/Header";
// import Footer from "@/components/Footer";
// import StarsCanvas from "@/components/StarBackground";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className="scroll-smooth">
//       <head>
//         {/* Google Fonts */}
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link
//           rel="preconnect"
//           href="https://fonts.gstatic.com"
//           crossOrigin=""
//         />
//         <link rel="icon" href="/br.png?v=1" />
//         <link
//           href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Grotesk:wght@300..700&display=swap"
//           rel="stylesheet"
//         />
//       </head>
//       <body className="bg-black custom-bg-dark overflow-x-hidden">
//         <StarsCanvas />
//         <div className="relative z-20">
//           <Header />
//           {children}
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }
