import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";
import StarsCanvas from "@/components/StarBackground";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <head>
        {/* Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Space+Grotesk:wght@300..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-black custom-bg-dark overflow-x-hidden">
        <StarsCanvas />
        <div className="relative z-20">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
